USE user_address;
CREATE TABLE User (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 number VARCHAR(20) NOT NULL
);

CREATE TABLE Address (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 location VARCHAR(255) NOT NULL,
 address VARCHAR(255) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES User(id)
);
